
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Tkinter designer\Accuracy Estimation\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1024x768")
window.configure(bg = "#181818")


canvas = Canvas(
    window,
    bg = "#181818",
    height = 768,
    width = 1024,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    554.0,
    68.0,
    1024.0,
    768.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    512.0,
    33.0,
    image=image_image_1
)

canvas.create_text(
    0.0,
    0.0,
    anchor="nw",
    text=" ACCURACY   ESTIMATION",
    fill="#FFFFFF",
    font=("Actor Regular", 30 * -1)
)

canvas.create_text(
    582.0,
    152.0,
    anchor="nw",
    text="RECOMMENDED CLASSIFIER",
    fill="#181818",
    font=("Actor Regular", 30 * -1)
)

canvas.create_text(
    402.0,
    165.0,
    anchor="nw",
    text="svcres",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

canvas.create_text(
    67.0,
    302.0,
    anchor="nw",
    text="XGBOOST",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

canvas.create_text(
    67.0,
    165.0,
    anchor="nw",
    text="SVC",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

canvas.create_text(
    402.0,
    300.0,
    anchor="nw",
    text="xgbres",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=644.0,
    y=641.0,
    width=334.0,
    height=69.0
)

canvas.create_text(
    67.0,
    438.0,
    anchor="nw",
    text="NAIVE BAYES",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

canvas.create_text(
    402.0,
    429.0,
    anchor="nw",
    text="nbres",
    fill="#FFFFFF",
    font=("Actor Regular", 32 * -1)
)

canvas.create_text(
    643.0,
    246.0,
    anchor="nw",
    text="result",
    fill="#1E1E1E",
    font=("Actor Regular", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
